#!/usr/bin/env bash
set -e

if [ -z "$(which aws)" ] || [ -z "$(which fzf)" ] || [ -z "$(which jq)" ]; then
  >&2 echo "# This script requires 'aws', 'fzf' and 'jq' to be installed"
  exit 1
fi

function clear-credentials {
  >&2 echo "# Clearing credentials"
  echo "unset AWS_ACCESS_KEY_ID"
  echo "unset AWS_SECRET_ACCESS_KEY"
  echo "unset AWS_PROFILE"
  >&2 echo "# To load credentials, run with:"
  >&2 echo "# eval \$($0)"
}

PROFILE=$(grep '\[.*\]' ~/.aws/credentials | sed '1 i\[none]' | fzf)
if [ ${PROFILE} = "[none]" ]; then
  clear-credentials
  exit 0
fi

AWS_PROFILE=$(echo "${PROFILE}" | sed 's/\[//;s/\]//')
>&2 echo "# Using AWS_PROFILE=${AWS_PROFILE}"
>&2 echo "# To load credentials, run with:"
>&2 echo "# eval \$($0)"
echo "export AWS_PROFILE=${AWS_PROFILE}"
