#+TITLE: Weisshorn

A new server for my Liechtenstein office based on previous AM5 hardware.

| Case | BeQuiet Pure Base 501          |
| CPU  | Ryzen 7950x, 16 cores, 80MB L3 |
| RAM  | Kingston Fury DDR5 5600, 64GB  |
| SSD  | Samsung 970 EVO 1TB            |
| SSD  | Samsung 870 EVO 2TB            |
| SSD  | Samsung 870 EVO 2TB            |

* TODO
- [X] SSH setup/forwarding
- [X] Describe disk setup
- [X] ZFS mirror on 2.5" SSDs
- [ ] Target offsite backups here
- [ ] Move services from liskamm here
  - [ ] Non-container mail? https://nixos-mailserver.readthedocs.io/en/latest/index.html
  - [ ] Non-container immich? https://wiki.nixos.org/wiki/Immich
  - [ ] Non-container nextcloud? https://nixos.wiki/wiki/Nextcloud

* Off-site backups

Mail data is backed up off-site to borgbase. The SSH key and passphrase need to
be installed once at =/root/keys/borg=:

#+begin_src sh
mkdir -p /root/keys/borg
bw config server https://passwords.ncoding.at
bw login
bw get attachment id_ed25519 --itemid $(bw list items --search BorgBase | jq -r '.[0].id') --output /root/keys/borg/id_ed25519
chmod 0400 /root/keys/borg/id_ed25519
bw get item BorgBase | jq -r '.fields[] | select(.name == "mail passphrase") | .value' > /root/keys/borg/mail.pass
#+end_src

Systemd services run every day to do backups. Check their status with:
#+begin_src sh
journalctl -u borgbackup-job-mail
#+end_src

Wrapper scripts can be used to list and restore backups:
#+begin_src sh
borg-job-mail list
borg-job-mail mount :: /mnt
#+end_src

* Wireguard tunnel to vpn.ncoding.li

Weisshorn runs behind NAT at the ncoding.li site. Public traffic for
=ncoding.at= hits the router at =vpn.ncoding.li= and is forwarded across a
persistent wireguard tunnel to =10.5.5.5= here. The client side is declared in
=vpn-ncoding.nix=; the matching peer entry and the DNAT/forward rules live on
the router.

** First-time key install

The router generates a key pair for each client and provides a =client.conf=.
Drop the private key into =/root/keys/wg/= once as root on weisshorn:

#+begin_src sh
mkdir -p /root/keys/wg
chmod 0700 /root/keys/wg
install -m 0400 /dev/stdin /root/keys/wg/private <<< "<private key from client.conf>"
#+end_src

The router's public key is already in =vpn-ncoding.nix=.

** Operations

Check the tunnel:
#+begin_src sh
sudo wg show wg0
systemctl status wireguard-wg0
journalctl -u wireguard-wg0 -e
#+end_src

* Disk setup

Operating system on the NVMe SSD and data on two 2TB SATA SSDs in separate ZFS
Raid1 pool. Contrary to the other systems, the root file system is ext4. I was
using the NixOS installer and just went with the default. The mounting of the
rootfs was cumbersome via zfs anyways and I don't need ZFS features on the NixOS
installation (snapshotting, compression, etc.)

#+begin_src
Disk /dev/nvme0n1: 931.51 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: Samsung SSD 970 EVO 1TB
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: E3DD2CF6-EFB8-4E89-B9DE-297F4577C532

Device              Start        End    Sectors   Size Type
/dev/nvme0n1p1       4096    2101247    2097152     1G EFI System
/dev/nvme0n1p2    2101248 1935070163 1932968916 921.7G Linux filesystem
/dev/nvme0n1p3 1935070164 1953525101   18454938   8.8G Linux swap
#+end_src

** Data on ZFS mirror pool

Any important data will be stored on a Raid1 mirror of the two SATA SSDs with some [[https://jrs-s.net/2018/08/17/zfs-tuning-cheat-sheet/][tuned settings]] and auto-snapshotting enabled by default for all data sets:
#+begin_src
zpool create \
  -o ashift=12 \
  -O acltype=posixacl \
  -O compression=lz4 \
  -O atime=off \
  -O com.sun:auto-snapshot=true \
  data \
  mirror \
  /dev/disk/by-id/ata-Samsung_SSD_870_EVO_2TB_S754NX0Y909823A \
  /dev/disk/by-id/ata-Samsung_SSD_870_EVO_2TB_S754NX0Y910081B
#+end_src
