encryption:
    tag: KEYRING

services:
  book:
    auth_endpoint: https://accounts.google.com/o/oauth2/auth
    auth_http_method: POST
    auth_params_mode: QueryString
    token_endpoint: https://accounts.google.com/o/oauth2/token
    token_http_method: POST
    token_params_mode: QueryString
    redirect_uri: http://localhost:8080
    auth_scope: https://mail.google.com/
    client_id: 220236565462-v12v9gsp4t7redjdc39ebstfij51gu35.apps.googleusercontent.com
    client_secret: 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
