name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nixos-build:
    name: Build NixOS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        hostname: ["liskamm", "eiger", "matterhorn"]
    steps:
      - uses: data-intuitive/reclaim-the-bytes@v2
        with:
          # NOTE: Remove more when needed, but these take also time
          # See https://github.com/marketplace/actions/reclaim-the-bytes
          remove-android-sdk: false
          remove-docker-images: false
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            log-lines = 1000
      - uses: cachix/cachix-action@v14
        with:
          name: ch1bo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build ".#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel"
