name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nixos-build:
    name: Build NixOS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        # TODO: fix disk space limits for ["eiger", "matterhorn"]
        hostname: ["liskamm"]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            log-lines = 1000
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: ch1bo
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix build ".#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel"
