name: Update systems
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * *' # every day at 00:00

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          inputs: nixpkgs nixpkgs-unstable home-manager cv
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated

  services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - owner: immich-app
            repo: immich
            file: hosts/liskamm/immich.nix
          - owner: dani-garcia
            repo: vaultwarden
            file: hosts/liskamm/vaultwarden.nix
          - owner: home-assistant
            repo: core
            file: hosts/liskamm/home-assistant.nix
          - owner: docker-mailserver
            repo: docker-mailserver
            file: hosts/liskamm/mailserver.nix
            mod: "(version) => version.slice(1)"
          - owner: nextcloud
            repo: server
            file: hosts/liskamm/nextcloud.nix
            mod: "(version) => version.slice(1)"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: "${{matrix.service.owner}}",
              repo: "${{matrix.service.repo}}",
            });
            console.log(latest);
            const mod = ${{ matrix.service.mod || '(x) => x' }};
            const newVersion = mod(latest.data.tag_name);
            await exec.exec('sed', ["-i", `s/version = ".*"/version = "${newVersion}"/`, "${{matrix.service.file}}"])

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          branch: update-services-${{matrix.service.owner}}-${{matrix.service.repo}}
          title: "Update ${{matrix.service.owner}}/${{matrix.service.repo}}"
          labels: |
            dependencies
            automated
